### ISSUE TITLE
Copyright Notice

### ISSUE THREAD

**Issue by tomac4t** [tomac4t/The-Code-Book-Chinese#1]
请转载时遵守许可证 [CC BY-NC-ND](https://github.com/tomac4t/the-code-book-chinese/blob/master/LICENSE)，做到署名、注明出处，注明许可证，不修改分发内容；如不能做到请删除侵权材料，谢谢。

Please follow the License [CC BY-NC-ND](https://github.com/tomac4t/the-code-book-chinese/blob/master/LICENSE), Thanks.

违反页面：https://briteming.blogspot.com/2020/01/blog-post_72.html

被通知人：@luckypoem @briteming

**Comment by luckypoem** [comment]
注明出处了 ，happy?  god  bless  u

**Comment by tomac4t** [comment]
https://lumendatabase.org/notices/20357713
