### ISSUE TITLE
已经删除你那篇文章

### ISSUE THREAD

**Issue by briteming** [tomac4t/The-Code-Book-Chinese#2]
谁稀罕你那文章，真是ridiculous.

**Comment by briteming** [comment]
rubbish一篇，已删除。开心吗？

**Comment by tomac4t** [comment]
@briteming 既然你觉得是垃圾，请一并把 https://github.com/luckypoem/the-code-book-chinese 给删了，你没有必要留一篇垃圾在你仓库。

**Comment by briteming** [comment]
是啊，我也也有此想法，没发现删除的地方，可以告诉一下删除的方法吗

**Comment by tomac4t** [comment]
@briteming: 
![](https://user-images.githubusercontent.com/47532693/79300635-e15b7a00-7f19-11ea-9162-2b6f4f96d151.png)

**Comment by tomac4t** [comment]
@briteming https://help.github.com/cn/github/administering-a-repository/deleting-a-repository

**Comment by luckypoem** [comment]
好了，删了。happy?
你得到什么了吗？就此赚了100万？还是我转发你的文章，我赚了100万？只能说明你是个mean guy.
我发现我博客上写的一些翻墙文章被人转载，有的注明了来源，有的没注明来源，那又怎样？i don't care.事实上，转载的人越多，说明人家越认可我的文章，对我来说，是一件feel honored之事。
你的境界跟网上那些copyleft网站，那些特意注明“可随意转载，版权没有”的网站的主人相差十万八千里。你就抱着你那“金贵”的文章一直睡大觉吧，等着100万从天而降。god bless u

**Comment by tomac4t** [comment]
第一次见不遵守许可证还理直气壮的，而且这种行为是违法的。

天天在别人 repo 发这些无脑[问题](https://github.com/klzgrad/naiveproxy/issues/34)，却连个删除仓库都不会，到底谁是垃圾？另外，我得提醒你，编辑、删除记录是没用的，任何事件都会在 [Github API](https://api.github.com/users/luckypoem/events) 留下永久痕迹，这也是为什么我敢确认 @briteming 和  @luckypoem 是同一个人，你会为你的行为负责的。

**Comment by tomac4t** [comment]
另外，英文原本本身就是 Copyleft 的 CC 许可，我只是沿用了，并不代表我吝啬；只能说你无知。要想使用只要做到许可证就行，可你连最基本的 BY 都做不到，甚至还删了许可证，Shame on you! @luckypoem
